name: End-to-end tests
on: [push]

jobs:
  tests:
    name: Cypress run e2e tests
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Admin portal tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Admin portal e2e tests'
          command: npm run cy:run_admin_portal
          # ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          CYPRESS_LMS_USER_EMAIL: ${{ secrets.CYPRESS_LMS_USER_EMAIL }}
          CYPRESS_LMS_USER_PASSWORD: ${{ secrets.CYPRESS_LMS_USER_PASSWORD }}
          CYPRESS_ADMIN_USER_EMAIL: ${{ secrets.CYPRESS_ADMIN_USER_EMAIL }}
          CYPRESS_ADMIN_USER_PASSWORD: ${{ secrets.CYPRESS_ADMIN_USER_PASSWORD }}
          CYPRESS_GMAIL_ID: ${{ secrets.CYPRESS_GMAIL_ID }}
          CYPRESS_GMAIL_CLIENT_ID: ${{ secrets.CYPRESS_GMAIL_CLIENT_ID }}
          CYPRESS_GMAIL_CLIENT_SECRET: ${{ secrets.CYPRESS_GMAIL_CLIENT_SECRET }}
          CYPRESS_GMAIL_ACCESS_TOKEN: ${{ secrets.CYPRESS_GMAIL_ACCESS_TOKEN }}
          CYPRESS_GMAIL_REFRESH_TOKEN: ${{ secrets.CYPRESS_GMAIL_REFRESH_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Authn MFE tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Authn MFE e2e tests'
          command: npm run cy:run_authn_mfe
        env:
          CYPRESS_LMS_USER_EMAIL: ${{ secrets.CYPRESS_LMS_USER_EMAIL }}
          CYPRESS_LMS_USER_PASSWORD: ${{ secrets.CYPRESS_LMS_USER_PASSWORD }}
          CYPRESS_GMAIL_ID: ${{ secrets.CYPRESS_GMAIL_ID }}
          CYPRESS_GMAIL_CLIENT_ID: ${{ secrets.CYPRESS_GMAIL_CLIENT_ID }}
          CYPRESS_GMAIL_CLIENT_SECRET: ${{ secrets.CYPRESS_GMAIL_CLIENT_SECRET }}
          CYPRESS_GMAIL_ACCESS_TOKEN: ${{ secrets.CYPRESS_GMAIL_ACCESS_TOKEN }}
          CYPRESS_GMAIL_REFRESH_TOKEN: ${{ secrets.CYPRESS_GMAIL_REFRESH_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
