name: End-to-end tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_LMS_USER_EMAIL: ${{ secrets.CYPRESS_LMS_USER_EMAIL }}
          CYPRESS_LMS_USER_PASSWORD: ${{ secrets.CYPRESS_LMS_USER_PASSWORD }}
          CYPRESS_ADMIN_USER_EMAIL: ${{ secrets.CYPRESS_ADMIN_USER_EMAIL }}
          CYPRESS_ADMIN_USER_PASSWORD: ${{ secrets.CYPRESS_ADMIN_USER_PASSWORD }}
          CYPRESS_GMAIL_ID: ${{ secrets.CYPRESS_GMAIL_ID }}
          CYPRESS_GMAIL_CLIENT_ID: ${{ secrets.CYPRESS_GMAIL_CLIENT_ID }}
          CYPRESS_GMAIL_CLIENT_SECRET: ${{ secrets.CYPRESS_GMAIL_CLIENT_SECRET }}
          CYPRESS_GMAIL_ACCESS_TOKEM: ${{ secrets.CYPRESS_GMAIL_ACCESS_TOKEM }}
          CYPRESS_GMAIL_REFRESH_TOKEN: ${{ secrets.CYPRESS_GMAIL_REFRESH_TOKEN }} 
        with:
          start: npm start
          # # we have already installed all dependencies above
          # install: false
          # record: true
          # command: bash -c 'npx cypress run --config-file admin_portal_stage.json'
          # group: All specs
          # ci-build-id: ${{ github.sha }}
          # # pluginsFile: false
        
      # - name: Run Tests
      #     uses: cypress-io/github-action@v1
      #     run: cy:run_admin_portal
      #     with:
      #       config-file: admin_portal_stage.json

  