name: End-to-end tests
on: [push]

jobs:
  cypress-run:
    name: every OS
    strategy:
      matrix:
        # run 2 copies of the current job in parallel
        # and they will load balance all specs
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        machines: [1, 2]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_LMS_USER_EMAIL: ${{ secrets.CYPRESS_LMS_USER_EMAIL }}
          CYPRESS_LMS_USER_PASSWORD: ${{ secrets.CYPRESS_LMS_USER_PASSWORD }}
          CYPRESS_ADMIN_USER_EMAIL: ${{ secrets.CYPRESS_ADMIN_USER_EMAIL }}
          CYPRESS_ADMIN_USER_PASSWORD: ${{ secrets.CYPRESS_ADMIN_USER_PASSWORD }}
          CYPRESS_GMAIL_ID: ${{ secrets.CYPRESS_GMAIL_ID }}
          CYPRESS_GMAIL_CLIENT_ID: ${{ secrets.CYPRESS_GMAIL_CLIENT_ID }}
          CYPRESS_GMAIL_CLIENT_SECRET: ${{ secrets.CYPRESS_GMAIL_CLIENT_SECRET }}
          CYPRESS_GMAIL_ACCESS_TOKEM: ${{ secrets.CYPRESS_GMAIL_ACCESS_TOKEM }}
          CYPRESS_GMAIL_REFRESH_TOKEN: ${{ secrets.CYPRESS_GMAIL_REFRESH_TOKEN }}
        with:
          config-file: config/admin_portal_stage.json
          group: Parallel 2x on ${{ matrix.os }}
          # on Mac and Linux we can use "npm start"
          start: npm start
          # but for this particular project on Windows we need a different start command
          start-windows: npm run start:ci:windows

  